var pets = [
    {
        name: 'Baxter',
        type: 'Dog',
        breed: 'Beagle',
        sex: 'Male',
        color: 'Tri-color (Black, Brown, White)',
        spayed: 'Yes',
        age: '5 Years',
        id: '34621',
        chip: '982000364789210',
        about: "Meet Baxter, a lovable Beagle with a knack for sniffing out fun! Baxter was loves long walks and has a keen sense of smell. He's great with kids and other dogs, making him the perfect family pet. His favorite pastime is chasing squirrels in the park and curling up for naps. Baxter is looking for a loving home where hecan share his endless affection and playful spirit.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Luna',
        type: 'Cat',
        breed: 'Maine Coon',
        sex: 'Female',
        color: 'Grey with white markings',
        spayed: 'Yes',
        age: '3 Years',
        id: '57281',
        chip: '981120019776432',
        about: "Luna is a majestic Maine Coon with a fluffy grey coat and striking white markings. She was found as a stray and has since become a gentle and affectionate companion. Luna enjoys perching on windowsills, watching birds, and being the center of attention. She's a bit shy at first but warms up quickly, especially if you have treats! Luna would thrive in a calm environment where she can relax and be pampered like the queen she is.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Sandy',
        type: 'Dog',
        breed: 'Golden Retriever',
        sex: 'Female',
        color: 'Golden',
        spayed: 'Yes',
        age: '7 Years',
        id: '41382',
        chip: '985112004567890',
        about: "Sandy is a heartwarming Golden Retriever with a golden coat as bright as her personality. Rescued from a neglectful situation, she has shown incredible resilience and love for life. Sandy is great with children and other pets, making her an ideal family dog. She enjoys outdoor adventures, especially swimming and fetching. Sandy is looking for a forever home where she can spread her joy and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Oliver',
        type: 'Cat',
        breed: 'Siamese',
        sex: 'Male',
        color: 'Seal Point',
        spayed: 'Yes',
        age: '2 Years',
        id: '62894',
        chip: '981120025678902',
        about: "Oliver is a sleek Siamese cat with striking blue eyes and a seal point coat. Found wandering in a neighborhood, he's adapted well to shelter life but is eager for a permanent home. Oliver is vocal, expressing his thoughts freely, and enjoys interactive playtime. He's affectionate and loves to be close to his human companions, often following them around the house. Oliver would do best in a home where he can receive plenty of attention and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Max',
        type: 'Dog',
        breed: 'Labrador Retriever',
        sex: 'Male',
        color: 'Chocolate',
        spayed: 'Yes',
        age: '4 Years',
        id: '47920',
        chip: '985120031478902',
        about: "Max is a charming Chocolate Labrador with a love for life and a tail that never stops wagging. Rescued from an overcrowded shelter, Max has shown immense gratitude and loyalty to his caregivers. He is full of energy and would thrive in a home with a backyard or regular access to outdoor activities. Max is great with children and other dogs, and he's always up for a game of fetch or a leisurely walk. His ideal home would be with an active family who can match his energy and zest for life.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Daisy',
        type: 'Cat',
        breed: 'Persian',
        sex: 'Female',
        color: 'White',
        spayed: 'Yes',
        age: '6 Years',
        id: '58329',
        chip: '981120036712345',
        about: "Daisy is a stunning white Persian cat with a luxurious coat and gentle demeanor. She was surrendered by an owner who could no longer care for her. Daisy is a bit of a diva and loves being the center of attention. She enjoys being groomed and will happily sit in your lap for hours. She's not fond of loud noises or fast movements, so a quiet and calm household would be ideal. Daisy is looking for a loving home where she can be pampered and adored.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Charlie',
        type: 'Dog',
        breed: 'Dachshund',
        sex: 'Male',
        color: 'Dapple',
        spayed: 'Yes',
        age: '3 Years',
        id: '49583',
        chip: '982000367829101',
        about: "Charlie is a spirited Dapple Dachshund with a playful personality. He was found as a stray and has since shown an incredible zest for life. Charlie loves exploring, whether it's a new trail or the corners of his home. He's a bit mischievous and enjoys hiding his toys. Charlie would do well in a home with an individual or family who enjoys fun and adventure. He's small but has a big heart and a lot of love to give.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'George',
        type: 'Cat',
        breed: 'British Shorthair',
        sex: 'Male',
        color: 'Blue (Gray)',
        spayed: 'Yes',
        age: '4 Years',
        id: '61029',
        chip: '985112007651234',
        about: "George is a robust British Shorthair with a striking blue-gray coat and a calm, dignified demeanor. Rescued from a busy city environment, he's adapted well to a quieter life. George enjoys leisurely days, lounging in sunny spots, and watching the world go by. He's not overly demanding for attention but appreciates a good chin scratch and will purr loudly in response. George is a bit reserved at first but becomes a loyal companion once he feels comfortable. He would be perfect for someone seeking a low-maintenance, independent cat.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Bella',
        type: 'Dog',
        breed: 'Boxer',
        sex: 'Female',
        color: 'Fawn with white markings',
        spayed: 'Yes',
        age: '1 Year',
        id: '50824',
        chip: '982000360234567',
        about: "Bella is a spirited Boxer with a fawn coat and charming white markings. She was rescued from a neglectful situation and has shown immense love and gratitude to her caregivers. Bella is energetic and playful, enjoying activities like running and playing fetch. She's great with older children and would thrive in a home where she can be active and engaged. Bella has a big personality and would be a fantastic companion for someone who loves adventure and fun.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },

    {
        name: 'Sophie',
        type: 'Cat',
        breed: 'Ragdoll',
        sex: 'Female',
        color: 'Seal point with blue eyes',
        spayed: 'Yes',
        age: '1 Year',
        id: '63845',
        chip: '985112008765432',
        about: "Sophie is a young Ragdoll cat with a soft seal point coat and mesmerizing blue eyes. She was found as a kitten and raised in a foster home. Sophie is incredibly affectionate, often seeking out laps to curl up in. She's playful and enjoys interactive toys, but she's also content to relax and watch the world go by. Sophie gets along well with other pets and would be an excellent addition to a loving family or individual looking for a gentle and loving companion.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Maximus',
        type: 'Dog',
        breed: 'German Shepherd',
        sex: 'Male',
        color: 'Black and Tan',
        spayed: 'No',
        age: '3 Years',
        id: '73829',
        chip: '985120036712345',
        about: "Maximus is a loyal German Shepherd with a sleek black and tan coat and an intelligent gaze. He's a quick learner and loves engaging in mentally stimulating activities like obedience training and puzzle games. Maximus is protective of his family and would make an excellent guard dog. Despite his imposing appearance, he's a gentle giant with a heart of gold. Maximus is looking for an experienced owner who can provide him with structure, training, and plenty of love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Milo',
        type: 'Cat',
        breed: 'Tabby',
        sex: 'Male',
        color: 'Orange Tabby',
        spayed: 'Yes',
        age: '2 Years',
        id: '89234',
        chip: '982000364712345',
        about: "Milo is a playful Orange Tabby with a mischievous streak and a love for adventure. He's always on the lookout for new toys to bat around and new heights to explore. Milo is incredibly curious and enjoys investigating every nook and cranny of his environment. He's affectionate and enjoys cuddling up with his human companions after a long day of play. Milo would do well in a home with plenty of enrichment opportunities and a patient owner who can keep up with his antics.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Lola',
        type: 'Dog',
        breed: 'French Bulldog',
        sex: 'Female',
        color: 'Fawn',
        spayed: 'Yes',
        age: '1 Year',
        id: '62345',
        chip: '981120036782345',
        about: "Lola is an adorable French Bulldog with a playful personality and expressive ears. She's a social butterfly who loves meeting new people and making friends wherever she goes. Lola enjoys short walks around the neighborhood and lounging on the couch with her favorite humans. She's a bit of a foodie and will do anything for a tasty treat. Lola is looking for a loving home where she can be showered with affection and continue spreading joy with her infectious personality.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },{
        name: 'Rocky',
        type: 'Dog',
        breed: 'Poodle',
        sex: 'Male',
        color: 'Apricot',
        spayed: 'Yes',
        age: '4 Years',
        id: '12345',
        chip: '982000364712345',
        about: "Rocky is an energetic Poodle with a curly apricot coat and a friendly disposition. He loves playing fetch in the park and going on long walks with his favorite humans. Rocky is intelligent and enjoys learning new tricks, especially if there are treats involved. He's great with children and other pets, making him an ideal family dog. Rocky is looking for an active household where he can receive plenty of exercise, mental stimulation, and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Molly',
        type: 'Cat',
        breed: 'Calico',
        sex: 'Female',
        color: 'Calico',
        spayed: 'Yes',
        age: '3 Years',
        id: '23456',
        chip: '981120036782345',
        about: "Molly is a beautiful Calico cat with a vibrant personality and a colorful coat. She's independent but enjoys spending time with her humans, especially if there's a warm lap to curl up on. Molly is playful and enjoys batting around toys and chasing laser pointers. She's a bit of a diva and loves being pampered with treats and attention. Molly is looking for a home where she can be the center of attention and receive all the love and affection she deserves.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Buddy',
        type: 'Dog',
        breed: 'Bulldog',
        sex: 'Male',
        color: 'Brindle',
        spayed: 'Yes',
        age: '2 Years',
        id: '34567',
        chip: '981120036712345',
        about: "Buddy is a lovable Bulldog with a brindle coat and a gentle demeanor. He's a bit of a couch potato and enjoys lounging around the house with his humans. Buddy is great with children and other pets, making him a wonderful family companion. He enjoys short walks around the neighborhood and sniffing around in the backyard. Buddy is looking for a laid-back household where he can relax and be showered with love and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Lucy',
        type: 'Cat',
        breed: 'Russian Blue',
        sex: 'Female',
        color: 'Gray',
        spayed: 'Yes',
        age: '2 Years',
        id: '45678',
        chip: '982000364712345',
        about: "Lucy is a sleek Russian Blue cat with a luxurious gray coat and striking green eyes. She's a bit shy at first but warms up quickly with gentle attention and affection. Lucy enjoys lounging in sunny spots by the window and watching birds in the garden. She's independent but enjoys spending time with her humans, especially if there's a cozy lap to curl up on. Lucy is looking for a quiet home where she can feel safe and loved.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Cooper',
        type: 'Dog',
        breed: 'Cocker Spaniel',
        sex: 'Male',
        color: 'Buff',
        spayed: 'Yes',
        age: '3 Years',
        id: '56789',
        chip: '981120036782345',
        about: "Cooper is a friendly Cocker Spaniel with a golden buff coat and soulful eyes. He's affectionate and enjoys cuddling up with his humans on the couch. Cooper is playful and enjoys fetching toys and going for walks in the park. He's great with children and other pets, making him a wonderful addition to any family. Cooper is looking for a loving home where he can receive plenty of attention, exercise, and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Lily',
        type: 'Cat',
        breed: 'Persian',
        sex: 'Female',
        color: 'White',
        spayed: 'Yes',
        age: '4 Years',
        id: '67890',
        chip: '981120036712345',
        about: "Lily is a stunning white Persian cat with a fluffy coat and a sweet temperament. She's a bit of a princess and enjoys being pampered with grooming sessions and treats. Lily is independent but enjoys spending time with her humans, especially if there's a warm lap to curl up on. She's quiet and well-mannered, making her an excellent companion for anyone seeking a calm and gentle pet. Lily is looking for a loving home where she can be adored and cherished.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Rocky',
        type: 'Dog',
        breed: 'Boxer',
        sex: 'Male',
        color: 'Fawn',
        spayed: 'Yes',
        age: '5 Years',
        id: '78901',
        chip: '981120036712345',
        about: "Rocky is a handsome Boxer with a fawn coat and a playful personality. He's energetic and enjoys running around in the backyard and going for long walks with his humans. Rocky is great with children and other pets, making him a wonderful family companion. He's affectionate and loves cuddling up with his humans after a day of play. Rocky is looking for a loving home where he can receive plenty of exercise, attention, and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Sophie',
        type: 'Cat',
        breed: 'Siamese',
        sex: 'Female',
        color: 'Seal Point',
        spayed: 'Yes',
        age: '3 Years',
        id: '89012',
        chip: '981120036712345',
        about: "Sophie is a beautiful Siamese cat with a sleek seal point coat and striking blue eyes. She's affectionate and enjoys spending time with her humans, especially if there's a warm lap to curl up on. Sophie is playful and enjoys chasing toys and climbing on cat trees. She's vocal and will let you know when she wants attention or treats. Sophie is looking for a loving home where she can be the center of attention and receive plenty of love and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Rocky',
        type: 'Dog',
        breed: 'Poodle',
        sex: 'Male',
        color: 'Apricot',
        spayed: 'Yes',
        age: '4 Years',
        id: '12345',
        chip: '982000364712345',
        about: "Rocky is an energetic Poodle with a curly apricot coat and a friendly disposition. He loves playing fetch in the park and going on long walks with his favorite humans. Rocky is intelligent and enjoys learning new tricks, especially if there are treats involved. He's great with children and other pets, making him an ideal family dog. Rocky is looking for an active household where he can receive plenty of exercise, mental stimulation, and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Molly',
        type: 'Cat',
        breed: 'Calico',
        sex: 'Female',
        color: 'Calico',
        spayed: 'Yes',
        age: '3 Years',
        id: '23456',
        chip: '981120036782345',
        about: "Molly is a beautiful Calico cat with a vibrant personality and a colorful coat. She's independent but enjoys spending time with her humans, especially if there's a warm lap to curl up on. Molly is playful and enjoys batting around toys and chasing laser pointers. She's a bit of a diva and loves being pampered with treats and attention. Molly is looking for a home where she can be the center of attention and receive all the love and affection she deserves.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Buddy',
        type: 'Dog',
        breed: 'Bulldog',
        sex: 'Male',
        color: 'Brindle',
        spayed: 'Yes',
        age: '2 Years',
        id: '34567',
        chip: '981120036712345',
        about: "Buddy is a lovable Bulldog with a brindle coat and a gentle demeanor. He's a bit of a couch potato and enjoys lounging around the house with his humans. Buddy is great with children and other pets, making him a wonderful family companion. He enjoys short walks around the neighborhood and sniffing around in the backyard. Buddy is looking for a laid-back household where he can relax and be showered with love and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Lucy',
        type: 'Cat',
        breed: 'Russian Blue',
        sex: 'Female',
        color: 'Gray',
        spayed: 'Yes',
        age: '2 Years',
        id: '45678',
        chip: '982000364712345',
        about: "Lucy is a sleek Russian Blue cat with a luxurious gray coat and striking green eyes. She's a bit shy at first but warms up quickly with gentle attention and affection. Lucy enjoys lounging in sunny spots by the window and watching birds in the garden. She's independent but enjoys spending time with her humans, especially if there's a cozy lap to curl up on. Lucy is looking for a quiet home where she can feel safe and loved.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Cooper',
        type: 'Dog',
        breed: 'Cocker Spaniel',
        sex: 'Male',
        color: 'Buff',
        spayed: 'Yes',
        age: '3 Years',
        id: '56789',
        chip: '981120036782345',
        about: "Cooper is a friendly Cocker Spaniel with a golden buff coat and soulful eyes. He's affectionate and enjoys cuddling up with his humans on the couch. Cooper is playful and enjoys fetching toys and going for walks in the park. He's great with children and other pets, making him a wonderful addition to any family. Cooper is looking for a loving home where he can receive plenty of attention, exercise, and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Lily',
        type: 'Cat',
        breed: 'Persian',
        sex: 'Female',
        color: 'White',
        spayed: 'Yes',
        age: '4 Years',
        id: '67890',
        chip: '981120036712345',
        about: "Lily is a stunning white Persian cat with a fluffy coat and a sweet temperament. She's a bit of a princess and enjoys being pampered with grooming sessions and treats. Lily is independent but enjoys spending time with her humans, especially if there's a warm lap to curl up on. She's quiet and well-mannered, making her an excellent companion for anyone seeking a calm and gentle pet. Lily is looking for a loving home where she can be adored and cherished.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Rocky',
        type: 'Dog',
        breed: 'Boxer',
        sex: 'Male',
        color: 'Fawn',
        spayed: 'Yes',
        age: '5 Years',
        id: '78901',
        chip: '981120036712345',
        about: "Rocky is a handsome Boxer with a fawn coat and a playful personality. He's energetic and enjoys running around in the backyard and going for long walks with his humans. Rocky is great with children and other pets, making him a wonderful family companion. He's affectionate and loves cuddling up with his humans after a day of play. Rocky is looking for a loving home where he can receive plenty of exercise, attention, and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Sophie',
        type: 'Cat',
        breed: 'Siamese',
        sex: 'Female',
        color: 'Seal Point',
        spayed: 'Yes',
        age: '3 Years',
        id: '89012',
        chip: '981120036712345',
        about: "Sophie is a beautiful Siamese cat with a sleek seal point coat and striking blue eyes. She's affectionate and enjoys spending time with her humans, especially if there's a warm lap to curl up on. Sophie is playful and enjoys chasing toys and climbing on cat trees. She's vocal and will let you know when she wants attention or treats. Sophie is looking for a loving home where she can be the center of attention and receive plenty of love and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Oscar',
        type: 'Dog',
        breed: 'Labrador Retriever',
        sex: 'Male',
        color: 'Black',
        spayed: 'No',
        age: '2 Years',
        id: '90123',
        chip: '982000364712345',
        about: "Oscar is a friendly Labrador Retriever with a shiny black coat and a wagging tail. He's energetic and loves going for walks, playing fetch, and swimming in the lake. Oscar is great with children and other pets, making him an ideal family dog. He's intelligent and eager to please, making training sessions a breeze. Oscar is looking for an active household where he can receive plenty of exercise, mental stimulation, and love.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Maggie',
        type: 'Cat',
        breed: 'Tabby',
        sex: 'Female',
        color: 'Brown Tabby',
        spayed: 'Yes',
        age: '4 Years',
        id: '91234',
        chip: '981120036712345',
        about: "Maggie is a sweet Tabby cat with a soft brown coat and a gentle disposition. She's affectionate and enjoys spending time with her humans, whether it's cuddling on the couch or playing with toys. Maggie is independent but enjoys being part of the family and will follow you around the house to keep you company. She's quiet and well-mannered, making her an excellent companion for anyone seeking a calm and loving pet. Maggie is looking for a loving home where she can be adored and cherished.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Bailey',
        type: 'Dog',
        breed: 'Golden Retriever',
        sex: 'Female',
        color: 'Golden',
        spayed: 'Yes',
        age: '3 Years',
        id: '92345',
        chip: '981120036712345',
        about: "Bailey is a beautiful Golden Retriever with a golden coat and a heart of gold. She's friendly and outgoing, always ready to greet you with a wagging tail and a big smile. Bailey is great with children and other pets, making her an ideal family companion. She enjoys outdoor adventures like hiking, swimming, and playing fetch. Bailey is looking for a loving home where she can be showered with attention, exercise, and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Simba',
        type: 'Cat',
        breed: 'Maine Coon',
        sex: 'Male',
        color: 'Orange Tabby',
        spayed: 'Yes',
        age: '5 Years',
        id: '93456',
        chip: '981120036712345',
        about: "Simba is a majestic Maine Coon with a fluffy orange tabby coat and a regal demeanor. He's independent but enjoys spending time with his humans, especially if there's a warm lap to curl up on. Simba is playful and enjoys chasing toys and exploring his environment. He's a bit of a hunter and loves watching birds from the window. Simba is looking for a quiet home where he can feel safe and loved.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Bentley',
        type: 'Dog',
        breed: 'Shih Tzu',
        sex: 'Male',
        color: 'White',
        spayed: 'Yes',
        age: '6 Years',
        id: '94567',
        chip: '981120036712345',
        about: "Bentley is a charming Shih Tzu with a fluffy white coat and a playful personality. He's affectionate and enjoys cuddling up with his humans on the couch. Bentley is great with children and other pets, making him a wonderful family companion. He enjoys short walks around the neighborhood and exploring new smells in the park. Bentley is looking for a loving home where he can receive plenty of attention, affection, and playtime.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Luna',
        type: 'Cat',
        breed: 'Siamese',
        sex: 'Female',
        color: 'Seal Point',
        spayed: 'Yes',
        age: '3 Years',
        id: '95678',
        chip: '981120036712345',
        about: "Luna is a beautiful Siamese cat with a sleek seal point coat and striking blue eyes. She's affectionate and enjoys spending time with her humans, especially if there's a warm lap to curl up on. Luna is playful and enjoys chasing toys and climbing cat trees. She's vocal and will let you know when she wants attention or treats. Luna is looking for a loving home where she can be the center of attention and receive plenty of love and affection.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Teddy',
        type: 'Dog',
        breed: 'Cavalier King Charles Spaniel',
        sex: 'Male',
        color: 'Tri-color',
        spayed: 'Yes',
        age: '2 Years',
        id: '96789',
        chip: '981120036712345',
        about: "Teddy is a lovable Cavalier King Charles Spaniel with a tri-color coat and expressive eyes. He's affectionate and enjoys cuddling up with his humans on the couch. Teddy is great with children and other pets, making him an ideal family companion. He enjoys leisurely walks around the neighborhood and exploring new scents in the park. Teddy is looking for a loving home where he can receive plenty of attention, affection, and playtime.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },
    {
        name: 'Zoe',
        type: 'Cat',
        breed: 'Ragdoll',
        sex: 'Female',
        color: 'Blue Point',
        spayed: 'Yes',
        age: '4 Years',
        id: '97890',
        chip: '981120036712345',
        about: "Zoe is a beautiful Ragdoll cat with a soft blue point coat and mesmerizing blue eyes. She's affectionate and enjoys spending time with her humans, especially if there's a warm lap to curl up on. Zoe is playful and enjoys chasing toys and playing with interactive games. She's gentle and well-mannered, making her an excellent companion for anyone seeking a calm and loving pet. Zoe is looking for a loving home where she can be adored and cherished.",
        status: ['Health checked', 'Vaccinations up to date', 'Regularly dewormed', 'Microchipped'],
    },


]